# Generated by Django 5.2.7 on 2026-04-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('phrase', models.CharField(max_length=255)),
                ('hint1', models.CharField(max_length=255)),
                ('hint2', models.CharField(max_length=255)),
            ],
        ),
    ]
